apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }} 
  namespace: {{ .Release.Namespace }} 
spec:
  selector:
    app: {{ .Release.Name }} 
  ports:
  - port: {{ .Values.webserver.service.port }}
    targetPort: {{ .Values.webserver.container.portName }} 
    name: http-server
    {{- if eq .Values.webserver.service.type "NodePort"}}
    nodePort: {{ .Values.webserver.service.nodePort }}
    {{- end }}
  type: {{ .Values.webserver.service.type }} 