apiVersion: flagger.app/v1beta1
kind: Canary
metadata:
  name: webserver
  namespace: test
spec:
  # deployment reference
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: webserver
  # the maximum time in seconds for the canary deployment
  # to make progress before it is rollback (default 600s)
  progressDeadlineSeconds: 60
  # HPA reference (optional)
  autoscalerRef:
    apiVersion: autoscaling/v2beta1
    kind: HorizontalPodAutoscaler
    name: webserver
  service:
    # service port number
    port: 80 
    # container port number or name (optional)
    targetPort: http-server
    # Istio gateways (optional)
    gateways:
    - webserver-gateway.eval.svc.cluster.local
    # Istio virtual service host names (optional)
    hosts:
    - webserver.com
    # Istio traffic policy (optional)
    trafficPolicy:
      tls:
        # use ISTIO_MUTUAL when mTLS is enabled
        mode: DISABLE
    # Istio retry policy (optional)
    retries:
      attempts: 3
      perTryTimeout: 1s
      retryOn: "gateway-error,connect-failure,refused-stream"
  analysis:
    # schedule interval (default 60s)
    interval: 1m
    # max number of failed metric checks before rollback
    threshold: 5
    # max traffic percentage routed to canary
    # percentage (0-100)
    maxWeight: 50
    # canary increment step
    # percentage (0-100)
    stepWeight: 10
    metrics:
    - name: error-percentage
      templateRef:
        name: error-percentage
        namespace: eval
      thresholdRange:
        max: 10
      interval: 1m
    - name: p90-latency 
      templateRef:
        name: p90-latency
        namespace: eval
      thresholdRange:
        max: 0.15
      interval: 1m
    webhooks:
      - name: acceptance-test
        type: pre-rollout
        url:  http://flagger-loadtester.test/
        timeout: 30s
        metadata:
          type: bash
          cmd: "curl -H 'host:webserver.com' http://webserver-canary.eval/hello"
      - name: load-test
        url: http://flagger-loadtester.test/
        timeout: 5s
        metadata:
          cmd: "hey -z 20m -q 10 -c 1 -H 'host:webserver.com' http://webserver-canary.eval/hello"