apiVersion: flagger.app/v1beta1
kind: MetricTemplate
metadata:
  name: error-percentage 
spec:
  provider:
    type: prometheus
    address: http://prometheus.istio-system:9090
  query: |
    sum(rate(webserver_errors{instance="webserver-canary.eval.svc.cluster.local:80"}[{{ interval }}]))
    /
    sum(rate(webserver_requests{instance="webserver-canary.eval.svc.cluster.local:80"}[{{ interval }}])) 
    *
    100
    or 
    on() vector(0)
---
apiVersion: flagger.app/v1beta1
kind: MetricTemplate
metadata:
  name: p90-latency 
spec:
  provider:
    type: prometheus
    address: http://prometheus.istio-system:9090
  query: |
    histogram_quantile(0.99, 
      rate(webserver_request_duration_seconds_bucket{instance="webserver-canary.eval.svc.cluster.local:80"}[{{ interval }}])
    ) > 0.02
    and 
    rate(webserver_request_duration_seconds_count{instance="webserver-canary.eval.svc.cluster.local:80"}[{{ interval }}]) > 1
    or 
    on() vector(0)