apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    errors: disabled
spec:
  template:
    spec:
      containers:
      - name: webserver
        image: nmalhotr/webserver:v1.0.1