{
 "title": "webserver",
 "time": { "from": "2020-05-06T20:58:10.012Z", "to": "2020-05-06T21:10:12.818Z" },
 "panels": [
  {
   "title": "status code returned per second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(webserver_requests{status!=\"200\"}[1m])) or on() vector(0)",
     "legendFormat": "non-200"
    },
    {
     "expr": "sum(rate(webserver_requests{status=\"200\"}[1m])) or on() vector(0)",
     "legendFormat": "200"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "graph",
   "description": "Rate of requests received by the server",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(webserver_requests{instance=\"webserver-canary.eval.svc.cluster.local:80\"}[1m])) by (instance, job)  or on() vector(0)"
    }
   ]
  },
  {
   "title": "90th percentile latencies",
   "type": "graph",
   "description": "Returns a boolean 0/1 if latency is > 10m",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, \n  rate(webserver_request_duration_seconds_bucket[1m])\n) > 0.02\nand \nrate(webserver_request_duration_seconds_count[1m]) > 1 \nor\non() \nvector(0)",
     "legendFormat": "> 20ms"
    },
    {
     "expr": "histogram_quantile(0.9, \n  rate(webserver_request_duration_seconds_bucket[1m])\n) > 0.01\nand \nrate(webserver_request_duration_seconds_count[1m]) > 1",
     "legendFormat": "> 10ms"
    },
    {
     "expr": "histogram_quantile(0.9, \n  rate(webserver_request_duration_seconds_bucket[1m])\n) > 0.005\nand \nrate(webserver_request_duration_seconds_count[1m]) > 1",
     "legendFormat": "> 5ms"
    },
    {
     "expr": "histogram_quantile(0.9, \n  rate(webserver_request_duration_seconds_bucket[1m])\n) > 0.05\nand \nrate(webserver_request_duration_seconds_count[1m]) > 1",
     "legendFormat": "> 50ms"
    }
   ]
  },
  {
   "title": "Percentage errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Percentage" }
   ],
   "targets": [
    {
     "expr": "sum(rate(webserver_errors[1m])) / sum(rate(webserver_requests[1m])) * 100 or on() vector(0)",
     "legendFormat": "% errors"
    }
   ]
  }
 ]
}